### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by ghost**
- [x] Code compliance with 1.1
- [x] Splitting big files

### CODE REVIEW

**Comment by pb82** [comment]
Hey,

thanks for the PR! I'm ignoring the variable, because it's not used in the message handler. Otherwise the compiler would warn about it. So ignoring it should be ok or am i missing something?

Good hint with :os.timestamp instead of :erlang.now!

**Comment by ghost** [comment]
The VM was complaining about it, that's the problem :p 

```
uniaika 22:18 (master ) ~/repos/Repox/Servus ❯❯ mix compile
Compiled lib/game.ex
Compiled lib/module.ex
Compiled lib/ConnectFour/gamefield.ex
lib/EchoModule/echo.ex:12: warning: the underscored variable "_state" is used after being set. A leading underscore indicates that the value of the variable should be ignored. If this is intended please rename the variable to remove the underscore
[…]
```

So I think it's better not to ignore the VM's warnings. They do make sense :heart:
There are also lots of warnings about unused variables (`a0`, `a1`, etc) but I'll take a look this week-end, and will expand this PR if I think we can improve the structure :)

**Comment by pb82** [comment]
Ok, the variable is actually used: in the code generated by the macro. So you're right ;-) Regarding the other warnings:

They should all occur in lib/ConnectFour/listhelp.ex. This module contains functions to manipulate and check a (ConnectFour) game field. To determine if a player has won we count the number of pieces of the same color. However we can only do this in vertical direction. In order to check for horizontal or diagonal wins, we rotate the game field. 

When only rotating 45° (diagonal win) a number of columns become superfluous: those less than four fields wide. It can be easily fixed by ignoring them (via wildcard) in the pattern in the `arrow_right/1` and `arrow_left/1` functions.

I just noticed that the server does not start with elixir 1.1.1 because of problems in config.exs. I will fix that.

So, if you want to expand your PR, i will not merge it now, but wait for further commits :-)

**Comment by ghost** [comment]
The server's up and running. I updated the first post with a list of the things I'll do.

**Comment by pb82** [comment]
That's great, thanks a lot! Actually that was exactly what i had in mind with config.exs. But you were quicker ;-)

**Comment by pb82** [comment]
I fixed the warnings about unused variables in listhelp.ex

**Comment by ghost** [comment]
@pb82 May I ask you to write some documentation about how to use the API with ConnectFour? :)

**Comment by pb82** [comment]
I'll add a README to ConnectFour. It should also be possible to write a test that goes through a whole game session with two players. I'll give that also a try.

**Comment by ghost** [comment]
Then maybe it would be wiser to track the tests in an other issue, don't you think?

**Comment by pb82** [comment]
:+1: 

Merged your fixes and refactoring, still working on the tests :)

**Comment by ghost** [comment]
Great :D

**Pull request merged**
